### PR TITLE
Add Utensils check in finding if Item is a Tool

### PR DESCRIPTION
**Pull request by Aeristoka**
Covers particularly "Cook's Utensils"

### CODE REVIEW

**Comment by kakaroto** [comment]
I thought that was handled! 🤦‍♂️ guess I missed it!

**Comment by Artemisthemp** [comment]
> I thought that was handled! 🤦‍♂️ guess I missed it!

I get a use tool when opening Cooking Utensils,

**Comment by Aeristoka** [comment]
> > I thought that was handled! 🤦‍♂️ guess I missed it!
> 
> I get a use tool when opening Cooking Utensils,

Screenshot it then.

**Comment by Artemisthemp** [comment]
> > > I thought that was handled! 🤦‍♂️ guess I missed it!
> > 
> > 
> > I get a use tool when opening Cooking Utensils,
> 
> Screenshot it then.

This is weird, I could have sworn there was a button earlier today and yet neither my Desktop or Laptop display it. 

So either the issue fix it self after a long time or I click Carpenter tools (most likely)

**Comment by Aeristoka** [comment]
> > > > I thought that was handled! 🤦‍♂️ guess I missed it!
> > > 
> > > 
> > > I get a use tool when opening Cooking Utensils,
> > 
> > 
> > Screenshot it then.
> 
> This is weird, I could have sworn there was a button earlier today and yet neither my Desktop or Laptop display it.
> 
> So either the issue fix it self after a long time or I click Carpenter tools (most likely)

I'll agree with most likely the mis-click onto another tool. There was literally 0 handling for something name "x Utensil". My PR put some in.

**Comment by kakaroto** [comment]
I would have switched the two lines so Wagon stays at the end and the 'includes' stay together, but it's a personal choice, not a bug and not a blocker. Thanks for the PR @Aeristoka.

**Pull request merged**
