### PR TITLE
Beyond20 inside frames

### PR DESCRIPTION
**Pull request by Ainias**
added `"all_frames": true` to the content scripts inside the manifest. This allows beyond20 to work inside iframes (which I want to have, because I'm writing a DM-Screen Plugin with an optional iframe for the character sheet)

### CODE REVIEW

**Comment by Aeristoka** [comment]
Looks like this also includes a CRLF -> LF conversion, if I'm looking at it right

**Comment by kakaroto** [comment]
Looks like it. I'll fix the CRLF locally as a separate commit then rebase so I can review properly then merge.
Thanks!

**Comment by Ainias** [comment]
Thanks! 
And sorry for the CRLF->LF conversion

**Comment by kakaroto** [comment]
Fixed the CRLF, then merged your change. Thanks!

**Pull request closed without merging**
