### PR TITLE
Fix for Advantage/Disadvantage Dropped Rolls

### LINKED ISSUE #255: DDB Digital Dice Integration fails to determine dropped die w/ Disadvantage/Advantage
image

Due (I believe) to changes for DDB Dice, there is no longer anything to compare at this point in code (both results being 0).

This results in the right side of the equation ALWAYS receiving .setDiscarded(true)

Advantaged Attack
image

Disadvantaged Attack
image

### PR DESCRIPTION
**Pull request by Aeristoka**
Fixes #255

Digital Dice implementation changed when rolls take place for all rolls
 (Digital Dice or not) this fix determines dropped rolls
 After Rolls have actually taken place in the new paradigm

### CODE REVIEW

**Comment by Aeristoka** [comment]
Tested and looks to be working Advantage/Disadvantage/Super Advantage/Super Disadvantage on DnDBeyond Integrated/Roll20/FVTT

**Comment by kakaroto** [comment]
Good catch!
This won't always work though because the advantage could be QUERY in the request, and so the getToHit would need to return the advantage result that the query gave.
Also, I believe there's another place where getToHit is called (skill check for example, where it's not building an attack)

**Comment by Aeristoka** [comment]
> Good catch!
> This won't always work though because the advantage could be QUERY in the request, and so the getToHit would need to return the advantage result that the query gave.
> Also, I believe there's another place where getToHit is called (skill check for example, where it's not building an attack)

I was worried there was a part of this I had missed. Where else does it need to be fixed up?

**Comment by kakaroto** [comment]
haven't checked, still waking up, just search for 'gettohit' in the file to see where else it's used :p

**Pull request closed without merging**
