### PR TITLE
Bugfix for monster attack parsing

### LINKED ISSUE #668: Piercer Attack Roll uses Dmg Roll instead
**Describe the bug**
In DNDB clicking the "Drop" button rolls the dmg instead of the attack roll.

**To Reproduce**
1. Go to https://www.dndbeyond.com/monsters/piercer
2. Click on"Drop"
3. See error: "the extension rolls the dmg roll instead of the attack. 

**Expected behavior**
Attack roll (and DMG roll) should be calculated

**Screenshots**
Screenshot 2021-01-26 233427
Screenshot 2021-01-27 101235

**Browser Info (please complete the following information):**
 - Browser Chrome
 - Version [e.g. 85] Version 88.0.4324.104 (Official Build) (64-bit). BDND: 2.3.0
 - Using Roll20.  

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Aeristoka**
Fixes #668
(Might break everything else, I'm bad at Regex)

### CODE REVIEW

**Comment by Aeristoka** [comment]
To be (slightly) more fair to myself, I tested across several simple (Goblin/Piercer) and several Complex (Ancient Green Dragon/Tarrasque/Acererak) monsters, and they all seemed to work fine.

**Comment by kakaroto** [comment]
Figgldygrak

**Comment by kakaroto** [comment]
lol, was trying to figure out why the regex had Gibletish in there, and I knew it was a word Wit told Dalinar so I was doubly confused until I found this PR 🤣

**Comment by dmportella** [comment]
I was wondering about that too XD

**Pull request merged**
