### PR TITLE
Bugfix for Ranger: Gathered Swarm

### PR DESCRIPTION
**Pull request by Aeristoka**
Now applies to rollAction and rollSpell as well, which is the more proper implementation RAW and RAI.

### CODE REVIEW

**Comment by kakaroto** [comment]
Who approved the previous implementation who did 2d6 instead of 1d8?! That person should get fired!
Thanks for this!

**Comment by Aeristoka** [comment]
> Who approved the previous implementation who did 2d6 instead of 1d8?! That person should get fired!
> Thanks for this!

You did...

**Comment by Aeristoka** [comment]
> Who approved the previous implementation who did 2d6 instead of 1d8?! That person should get fired!
> Thanks for this!

More seriously, I believe it was originally implemented when it was UA, and I think this was a holdover from the UA version, then never got fixed.

**Comment by kakaroto** [comment]
Ah, that makes sense then! Thanks for this fix and catching the damage change :)

**Pull request merged**
