### PR TITLE
Implement Grave Cleric: Circle of Mortality

### PR DESCRIPTION
**Pull request by Aeristoka**
Maximizes healing on Creatures with 0 HP
Toggles off after usage
https://www.dndbeyond.com/classes/cleric#GraveDomain

### CODE REVIEW

**Comment by kakaroto** [comment]
Noice!

**Comment by Aeristoka** [comment]
> Noice!

Got a player doing a Grave Cleric right now, last session she punched out a fellow player to Max Heal him back up. Wonderful RP moment.

Then I was like "Wait... I can make this happen super easy via Beyond20..."

**Comment by kakaroto** [comment]
> > Noice!
> 
> Got a player doing a Grave Cleric right now, last session she punched out a fellow player to Max Heal him back up. Wonderful RP moment.
> 
> Then I was like "Wait... I can make this happen super easy via Beyond20..."

hehe, yeah, that's pretty cool.
Also, I always knew that half of the special feats you added were because your players needed them during a game! :D

**Comment by Aeristoka** [comment]
> > > Noice!
> > 
> > 
> > Got a player doing a Grave Cleric right now, last session she punched out a fellow player to Max Heal him back up. Wonderful RP moment.
> > Then I was like "Wait... I can make this happen super easy via Beyond20..."
> 
> hehe, yeah, that's pretty cool. Also, I always knew that half of the special feats you added were because your players needed them during a game! :D

Started that way, then super swerved into me reading through every new Subclass/Feat/etc. that came out and implementing those. 😄

**Pull request merged**
