### PR TITLE
Fix for Beyond20RollRenderer Rolls

### PR DESCRIPTION
**Pull request by Aeristoka**
Seems to have slipped last night

### CODE REVIEW

**Comment by cronosaurus** [comment]
unfortunately i am just a user of deyond20 and dont know how to program. can you explain exactly how to fix this?

**Comment by Aeristoka** [comment]
> unfortunately i am just a user of deyond20 and dont know how to program. can you explain exactly how to fix this?

All you need is to load the extension from the source :

If you already have Beyond20 installed from the Chrome or Firefox stores, disable it.
Download the extension from [github](https://github.com/Aeristoka/Beyond20/archive/beyond20rollrenderer-damage_rolls-fix.zip)
Extract the zip file in a directory of your choice
(Chrome)
Go to Chrome Extensions page (Menu->More Tools->Extensions)
Enable Developer Mode (Top-right corner)
Click on the 'Load Unpacked' button
Select the Directory where you extracted this extension

**Comment by Aeristoka** [comment]
Hoping we'll have a 2.2.1 with this and a few other fixes soon

At that point you'll need to remove the dev version, and update to that

**Comment by cronosaurus** [comment]
THANK YOU SO MUCH!

**Pull request merged**
