### PR TITLE
GetHitCritCard Add render and content

### PR DESCRIPTION
**Pull request by captify-ochekhovskyi**
Little feature for your awesome plugin. 
That little script just add possibility to chose new home-brew with getting cards with effects when character get crit/fail .

### CODE REVIEW

**Comment by Aeristoka** [comment]
Can you post Screenshots of what the results are from what you've added here?

**Comment by captify-ochekhovskyi** [comment]
image

Screenshot from 2021-04-05 02-13-40
Screenshot from 2021-04-05 02-12-41

**Comment by captify-ochekhovskyi** [comment]
function just parse results, get random chaise  and getting content based on types of damage. After that render result on Roll20 page.

**Comment by kakaroto** [comment]
Hi @captify-ochekhovskyi,
Thank you for the PR, however, I cannot accept this change as it adds something very specific and opinionated. I cannot have a guarantee that every one of those 52 quotes are part of the public domain and aren't infringing on anybody's copyright, and their contents might not be suitable for every group. A more generic solution where users can define their own "roll table" of results would make more sense, but I would still not accept it as that would be a quite significant feature that I don't believe fits within the purpose of Beyond20, which remains to simplify rolling from D&D Beyond. 
Thanks for understanding.

**Comment by captify-ochekhovskyi** [comment]
Ok. thank you for your time.

**Pull request closed without merging**
