### PR TITLE
Add integration with SendingStone

### PR DESCRIPTION
**Pull request by craigspaeth**
Hi 👋

I'm building a video conferencing meets VTT app called [SendingStone](https://www.sendingstone.com/) and some early users have expressed interest in integrating with your wonderful chrome extension. I'd love to start off with syncing over dice rolls.

This enables that by simply forwarding over all messages from D&D Beyond with `postMessage`. SendingStone will then parse the message body on its side and do what it needs.

https://user-images.githubusercontent.com/555859/111938448-9635d980-8a8f-11eb-80f4-0b11864eb24b.mov

Thanks for your consideration!

### CODE REVIEW

**Comment by Aeristoka** [comment]
https://beyond20.here-for-more.info/faq#can-you-add-support-for-insert-new-vtt-name

**Comment by craigspaeth** [comment]
Darn—I should have read the docs closer. Thank you for your great work on this chrome extension regardless!

**Comment by Aeristoka** [comment]
> Darn—I should have read the docs closer. Thank you for your great work on this chrome extension regardless!

No worries, nothing wrong with you maintaining your own fork for them to use, but KaKaRoTo has made his position on official support pretty clear

**Comment by kakaroto** [comment]
Hey Craig!
Nice looking site, I really like its vibe!
Thanks for the PR. As @Aeristoka pointed out, I've decided against supporting more VTTs at this time for the reasons outlined in the FAQ, but you can always fork Beyond20 and release it just for your platform.
In that case, in the spirit of open source, I'd appreciate receiving further PRs that improve the core functionality of Beyond20 if you were to add/fix something from your side.
Thanks and good luck with your project!

**Comment by kakaroto** [comment]
Hi @craigspaeth,
Just following up on this btw, we've added in the recent Beyond20 release the ability for sites to integrate directly with Beyond20 via DOM events, which would mean you wouldn't need to have a fork of Beyond20 anymore.
You can read more about it here: https://beyond20.here-for-more.info/api#the-dom-api
Let me know if you have any questions!

**Pull request closed without merging**
