### PR TITLE
Fix - issue with action rolls from DDB changes

### PR DESCRIPTION
**Pull request by Azmoria**
This change should resolve the action rolling issues from DDB changes today. Looks like they changed the sidebar info classes.

### CODE REVIEW

**Comment by jtbg** [comment]
Tested and confirmed that this change fixes #1131 and #1132

**Review by jtbg — APPROVED** [review]

**Comment by Kodokbotak** [comment]
how do you apply this fix?

**Comment by stonesteel25** [comment]
I have tried this with the developer version and it doesn't resolve it on my end

**Comment by jtbg** [comment]
> how do you apply this fix?

after code review, it will be merged and the extension will be updated on the Chrome/firefox/etc store. If you desperately need a fix in the meantime, join the discord and I can share a dev build for you

**Comment by jtbg** [comment]
> I have tried this with the developer version and it doesn't resolve it on my end

@stonesteel25 any chance you could you post the `crx`/`xpi` package of your build? 

> how do you apply this fix?

@Kodokbotak after code review, it will be merged and the extension will be updated on the Chrome/firefox/etc store. If you desperately need a fix in the meantime, join the discord and I can share a dev build for you

**Comment by dmportella** [comment]
that worked for me

I would change or remove the if statement

if we want to keep the if statement in propertyListToDict adding toLowerCase() to the filter also fixes the problem.

```
        // April 2024 website redesign now uses dynamic class names with styled components
        if (labelElement.length === 0 || valueElement.length === 0) {
            labelElement = prop.children().filter((i, el) => el.className.toLowerCase().includes("label"));
            valueElement = prop.children().filter((i, el) => el.className.toLowerCase().includes("value"));
        }
```

**Comment by kakaroto** [comment]
> that worked for me
> 
> I would change or remove the if statement
> 
> if we want to keep the if statement in propertyListToDict adding toLowerCase() to the filter also fixes the problem.
> 
> ```
>         // April 2024 website redesign now uses dynamic class names with styled components
>         if (labelElement.length === 0 || valueElement.length === 0) {
>             labelElement = prop.children().filter((i, el) => el.className.toLowerCase().includes("label"));
>             valueElement = prop.children().filter((i, el) => el.className.toLowerCase().includes("value"));
>         }
> ```
> 
> Both changes fix the problem.



> that worked for me
> 
> I would change or remove the if statement
> 
> if we want to keep the if statement in propertyListToDict adding toLowerCase() to the filter also fixes the problem.
> 
> ```
>         // April 2024 website redesign now uses dynamic class names with styled components
>         if (labelElement.length === 0 || valueElement.length === 0) {
>             labelElement = prop.children().filter((i, el) => el.className.toLowerCase().includes("label"));
>             valueElement = prop.children().filter((i, el) => el.className.toLowerCase().includes("value"));
>         }
> ```
> 
> Both changes fix the problem.

Why did they need to change the class name from `Label` to `label` ? 😭 
Thanks for the fix, I'll merge this one, and also apply the change to the lowercase label/value class names

**Comment by dmportella** [comment]
> Why did they need to change the class name from `Label` to `label` ? 😭 Thanks for the fix, I'll merge this one, and also apply the change to the lowercase label/value class names

I know T,  T silly changes not sure why they did that for, what worries me most was that they added styled components a terrible module - where I work we are spending $$$$$ to remove it

**Pull request merged**
