### PR TITLE
added missing await for the async call

### PR DESCRIPTION
**Pull request by dmportella**
For the DDB DOm changes to work needed to add the await for the async function the promise was not getting fulfilled once that is done it all works

### CODE REVIEW

**Comment by dmportella** [comment]
@kakaroto I cant message on discord, error 500 for some reason i found an issue with one of the changes (dom changes) the dice.js base for dndbeyond was missing the await keyword

**Comment by kakaroto** [comment]
Ah, thanks, good catch. I'm glad I waited for release 😁 
And yeah, Discord is completely broken right now.
https://discordstatus.com/

**Comment by dmportella** [comment]
> Ah, thanks, good catch. I'm glad I waited for release 😁 And yeah, Discord is completely broken right now. https://discordstatus.com/

yep, i tested all of the other items but there one I am not sure how to test

image

image

**Comment by dmportella** [comment]
AH i got it XD didnt know you could set creature HP there
image

**Comment by dmportella** [comment]
its is working

**Pull request merged**
