### PR TITLE
Minor CSS changes for displaying rolls in DDB

### PR DESCRIPTION
**Pull request by LorduFreeman**
Added font-styling for rolls directly in DnDBeyond, when no VTT is found. Beyond uses Roboto which is now used for the rolls as well.

TODO/Future:
Not sure how complex of a task this is but further styling the rolls to look just like the DDB design would be nice. Maybe even somehow grab the Underdark design if the mode is enabled.

### CODE REVIEW

**Comment by Aeristoka** [comment]
Man, that looks so nice... must not try to talk @kakaroto into releasing another hotfix with JUST this... Must not...

**Comment by Aeristoka** [comment]
@LorduFreeman Can something be helped so that the damages like this are more consistent? I can't remember the state of that:
image

**Comment by LorduFreeman** [comment]
Ah snap, looks like the `last-child` formatting needs to go because of this. Usually the last roll entry need to get formatted but when a crit with a single damage source happens, that is not sufficient (the last two lines need to be formatted).

The best solution now is removing the `last-child` css again and instead using newly created classes for a line output that shows damage of any kind.

**Comment by LorduFreeman** [comment]
Fixed that problem, I needed to add the new class tag but now stuff looks nice:
image
image

pushed the change just now but I'm still not satisfied with the colours. Decided on blue for totals, red for crits and green for healing for now.

**Comment by LorduFreeman** [comment]
Turns out I made the regular damages too big, so I compromised like this:
image
image

The single damage rolls on spell look more unassuming but I love how stacked damages on complicated attacks look.

**Comment by LorduFreeman** [comment]
I noticed the dev version just needs the files in /dist changed to apply the changes.

Only thing left now is: Currently it is impossible to style a single damage result display differently than a stacked one. Having this would be useful for applying a bigger font and styling similar to the attack roll to single attack damage rolls and spells like the Dissonant Whispers in the picture up there. 
Adding some comparison for `damage_rolls.length === 1` and then adding a new class tag to that would be needed.

**Comment by LorduFreeman** [comment]
Decided to remove the blue color on total damage. Regular damage is now non-coloured, Crit damage is dark red, healing is green.
image

**Comment by Aeristoka** [comment]
> I noticed the dev version just needs the files in /dist changed to apply the changes.
> 
> Only thing left now is: Currently it is impossible to style a single damage result display differently than a stacked one. Having this would be useful for applying a bigger font and styling similar to the attack roll to single attack damage rolls and spells like the Dissonant Whispers in the picture up there.
> Adding some comparison for `damage_rolls.length === 1` and then adding a new class tag to that would be needed.

are you running `npm run build` ?

NEVER edit things in dist

**Comment by LorduFreeman** [comment]
> > I noticed the dev version just needs the files in /dist changed to apply the changes.
> > Only thing left now is: Currently it is impossible to style a single damage result display differently than a stacked one. Having this would be useful for applying a bigger font and styling similar to the attack roll to single attack damage rolls and spells like the Dissonant Whispers in the picture up there.
> > Adding some comparison for `damage_rolls.length === 1` and then adding a new class tag to that would be needed.
> 
> are you running `npm run build` ? https://github.com/kakaroto/Beyond20#build
> 
> NEVER edit things in dist

Nope, I'm not (a little new to this). I thought the dev version is already built and I do not need to re-build.

**Comment by Aeristoka** [comment]
> > > I noticed the dev version just needs the files in /dist changed to apply the changes.
> > > Only thing left now is: Currently it is impossible to style a single damage result display differently than a stacked one. Having this would be useful for applying a bigger font and styling similar to the attack roll to single attack damage rolls and spells like the Dissonant Whispers in the picture up there.
> > > Adding some comparison for `damage_rolls.length === 1` and then adding a new class tag to that would be needed.
> > 
> > 
> > are you running `npm run build` ? https://github.com/kakaroto/Beyond20#build
> > NEVER edit things in dist
> 
> Nope, I'm not (a little new to this). I thought the dev version is already built and I do not need to re-build.

Ah, ok, you did a REALLY good job on the CSS changes without rebuilding 😂 .

But yep, make a change, testing ONLY the Chrome Extension, gotta `npm run build` then reload the extension in the Chrome Extensions menu (with Developer Mode enabled)

**Comment by kakaroto** [comment]
Humm.. I'm not a fan of how it looks now with each line being "individually wrapped", especially with the red on the crit lines. I do like the blue/red for the total damages, but not for the regular lines.

image

I prefer how the damage lines look in here : 
image

but without the red outline for crit.


As for dev, I just do `npm run gulp` and it will continually watch for any changes to the sources and rebuild it into the dist folder, and you just load the `build/chrome/` or `build/firefox` folders in your local browser, and reload it after you make a change to see the update.

Thanks!

**Comment by LorduFreeman** [comment]
> Humm.. I'm not a fan of how it looks now with each line being "individually wrapped", especially with the red on the crit lines. I do like the blue/red for the total damages, but not for the regular lines.

That's true, individually wrapped lines make quite an impact visually, I've removed that formatting again. Removed the blue for total regular damage as well because it does not correspond with regular damage styling at all.

image
image
image

Now I still have not found any way to format short attacks without affecting longer roll stacks.

**Comment by Aeristoka** [comment]
> > Humm.. I'm not a fan of how it looks now with each line being "individually wrapped", especially with the red on the crit lines. I do like the blue/red for the total damages, but not for the regular lines.
> 
> That's true, individually wrapped lines make quite an impact visually, I've removed that formatting again. Removed the blue for total regular damage as well because it does not correspond with regular damage styling at all. However I like having a kind of marker for all the critical damage parts, so I tried the red line at the left side - looks quite nice and subtle enough.
> 
> imageimageimage
> 
> Now I still have not found any way to format short attacks without affecting longer roll stacks.

I like that a whole bunch.

What do you think @kakaroto ?

**Comment by LorduFreeman** [comment]
Found another tiny issue: With Critical Two-Handed damage, the displayed text is too long to be contained in a single row:
image

**Comment by Aeristoka** [comment]
> Found another tiny issue: With Critical Two-Handed damage, the displayed text is too long to be contained in a single row:
> imageimage
> 
> Adjusting font-size makes the text relatively small again. Another option would be removing the "Critical" text and replacing it with a Crit Icon of some kind

I like it a little bit smaller I think.

**Comment by kakaroto** [comment]
> I like that a whole bunch.
> 
> What do you think @kakaroto ?

img

**Comment by kakaroto** [comment]
> 
> I like it a little bit smaller I think.

Yeah, I think smaller for that total is not looking so bad. I also very much like that left-border you did there for the crit, so much better than way! 👍

**Comment by Aeristoka** [comment]
Just trying this out, I'm seeing this:
image

It appears to be from this:
image

**Comment by LorduFreeman** [comment]
> Just trying this out, I'm seeing this:

Minor oversight, fixed!

**Comment by LorduFreeman** [comment]
Side question: Once DDB can display rolls like native rolls in Foundry (https://github.com/kakaroto/Beyond20/issues/218), does this styling become unnecessary?

**Comment by Aeristoka** [comment]
> Side question: Once DDB can display rolls like native rolls in Foundry (#218), does this styling become unnecessary?

It just won't apply, but tons of people will use it without using that feature still I'm sure.

**Comment by Aeristoka** [comment]
This has been looking pretty for me for two sessions now, merging.

**Comment by kakaroto** [comment]
Thank you! 🥳

**Pull request merged**
